"""External academic source adapters for the Librarian agent.

All HTTP calls go through this module — agents must never call httpx directly
(see docs/agents/librarian.md §Invariants). Two adapters are wired in Phase 1:
  - SemanticScholarAdapter  (JSON API v1 graph endpoint)
  - ArXivAdapter            (Atom feed API)

Each adapter implements `SourceAdapter` (a Protocol). The `DiscoveryService`
fans them out in parallel and merges results.
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from datetime import UTC, datetime
from typing import Protocol
from uuid import uuid4

import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

from app.config import get_settings
from app.models.schemas import Paper
from app.utils.logging import get_logger

_log = get_logger(__name__)

# Shared async client (re-used across adapter calls within a single request).
_HTTP_TIMEOUT = httpx.Timeout(30.0)


# ---------------------------------------------------------------------------
# Protocol that every source adapter must satisfy
# ---------------------------------------------------------------------------


class SourceAdapter(Protocol):
    async def search(
        self, query: str, max_results: int, client: httpx.AsyncClient
    ) -> list[Paper]: ...


# ---------------------------------------------------------------------------
# Semantic Scholar adapter
# ---------------------------------------------------------------------------

_SS_BASE = "https://api.semanticscholar.org/graph/v1"
_SS_FIELDS = "paperId,externalIds,title,authors,year,abstract,citationCount,openAccessPdf"


class SemanticScholarAdapter:
    """Queries the Semantic Scholar Graph API v1.

    An optional API key raises the rate limit from 100 to 1 000 req/min.
    """

    def __init__(self, api_key: str = "") -> None:
        self._api_key = api_key

    def _headers(self) -> dict[str, str]:
        if self._api_key:
            return {"x-api-key": self._api_key}
        return {}

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=8))
    async def search(self, query: str, max_results: int, client: httpx.AsyncClient) -> list[Paper]:
        params: dict[str, str | int] = {
            "query": query,
            "limit": min(max_results, 100),
            "fields": _SS_FIELDS,
        }
        try:
            resp = await client.get(
                f"{_SS_BASE}/paper/search",
                params=params,
                headers=self._headers(),
                timeout=_HTTP_TIMEOUT,
            )
            resp.raise_for_status()
        except httpx.HTTPStatusError as exc:
            _log.warning("semantic_scholar_error", status=exc.response.status_code, query=query)
            return []

        data = resp.json()
        papers: list[Paper] = []
        now = datetime.now(tz=UTC)
        for item in data.get("data", []):
            ext_ids: dict[str, str] = item.get("externalIds") or {}
            doi = ext_ids.get("DOI", "")
            arxiv_id = ext_ids.get("ArXiv", "")
            external_id = doi or arxiv_id or item.get("paperId", "")
            if not external_id:
                continue

            pdf_url: str | None = None
            oap = item.get("openAccessPdf")
            if oap and oap.get("url"):
                pdf_url = oap["url"]

            authors = [a.get("name", "") for a in (item.get("authors") or [])]
            papers.append(
                Paper(
                    id=uuid4(),
                    project_id=uuid4(),  # replaced by caller
                    source="semantic_scholar",
                    external_id=external_id,
                    title=item.get("title") or "",
                    authors=authors,
                    year=item.get("year"),
                    abstract=f"<paper_abstract>{item.get('abstract')}</paper_abstract>"
                    if item.get("abstract")
                    else None,
                    pdf_url=pdf_url,  # type: ignore[arg-type]
                    citation_key="",  # generated by Librarian after dedup
                    citation_count=item.get("citationCount"),
                    approved=False,
                    added_at=now,
                )
            )

        _log.info("semantic_scholar_results", query=query, count=len(papers))
        return papers


# ---------------------------------------------------------------------------
# ArXiv adapter
# ---------------------------------------------------------------------------

_ARXIV_BASE = "http://export.arxiv.org/api/query"
_ARXIV_NS = "http://www.w3.org/2005/Atom"
_ARXIV_OAI = "http://arxiv.org/schemas/atom"


class ArXivAdapter:
    """Queries the ArXiv Atom Feed API (no API key required)."""

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=8))
    async def search(
        self,
        query: str,
        max_results: int,
        client: httpx.AsyncClient,
        categories: list[str] | None = None,
    ) -> list[Paper]:
        # Build the search_query string with optional ArXiv category filters.
        search_expr = f"all:{query}"
        if categories:
            cat_expr = " OR ".join(f"cat:{c}" for c in categories[:5])
            search_expr = f"({search_expr}) AND ({cat_expr})"

        params: dict[str, str | int] = {
            "search_query": search_expr,
            "max_results": min(max_results, 100),
            "sortBy": "relevance",
            "sortOrder": "descending",
        }
        try:
            resp = await client.get(_ARXIV_BASE, params=params, timeout=_HTTP_TIMEOUT)
            resp.raise_for_status()
        except httpx.HTTPStatusError as exc:
            _log.warning("arxiv_error", status=exc.response.status_code, query=query)
            return []

        root = ET.fromstring(resp.text)
        ns = {"atom": _ARXIV_NS}
        papers: list[Paper] = []
        now = datetime.now(tz=UTC)

        for entry in root.findall("atom:entry", ns):
            title_el = entry.find("atom:title", ns)
            title = (title_el.text or "").strip().replace("\n", " ") if title_el is not None else ""
            if not title:
                continue

            # ArXiv ID is the last segment of the <id> element URL.
            id_el = entry.find("atom:id", ns)
            arxiv_url = id_el.text.strip() if id_el is not None and id_el.text else ""
            arxiv_id = arxiv_url.split("/")[-1] if arxiv_url else ""
            if not arxiv_id:
                continue

            abstract_el = entry.find("atom:summary", ns)
            abstract = (
                f"<paper_abstract>{abstract_el.text.strip()}</paper_abstract>"
                if abstract_el is not None and abstract_el.text
                else None
            )

            published_el = entry.find("atom:published", ns)
            year: int | None = None
            if published_el is not None and published_el.text:
                try:
                    year = int(published_el.text[:4])
                    if year < now.year - 5:  # Filter out papers older than 5 years
                        continue
                except ValueError:
                    pass

            authors: list[str] = []
            for a in entry.findall("atom:author", ns):
                name_el = a.find("atom:name", ns)
                if name_el is not None and name_el.text:
                    authors.append(name_el.text.strip())

            pdf_url = f"https://arxiv.org/pdf/{arxiv_id}"

            papers.append(
                Paper(
                    id=uuid4(),
                    project_id=uuid4(),  # replaced by caller
                    source="arxiv",
                    external_id=arxiv_id,
                    title=title,
                    authors=authors,
                    year=year,
                    abstract=abstract,
                    pdf_url=pdf_url,  # type: ignore[arg-type]
                    citation_key="",  # generated by Librarian after dedup
                    approved=False,
                    added_at=now,
                )
            )

        _log.info("arxiv_results", query=query, count=len(papers))
        return papers


# ---------------------------------------------------------------------------
# DiscoveryService — fans out all adapters
# ---------------------------------------------------------------------------


class DiscoveryService:
    """Aggregates results from multiple source adapters in parallel."""

    def __init__(self) -> None:
        settings = get_settings()
        self._adapters: list[SourceAdapter] = [
            SemanticScholarAdapter(api_key=settings.semantic_scholar_api_key),
            ArXivAdapter(),
        ]

    async def search(
        self,
        queries: list[str],
        max_per_source: int = 30,
        arxiv_categories: list[str] | None = None,
    ) -> list[Paper]:
        """Search all adapters for all queries in parallel, return merged list."""
        import asyncio

        limits = httpx.Limits(max_connections=20, max_keepalive_connections=5)
        async with httpx.AsyncClient(follow_redirects=True, limits=limits) as client:
            tasks = []
            for query in queries:
                for adapter in self._adapters:
                    if isinstance(adapter, ArXivAdapter):
                        tasks.append(
                            adapter.search(
                                query, max_per_source, client, categories=arxiv_categories
                            )
                        )
                    else:
                        tasks.append(adapter.search(query, max_per_source, client))
            results_nested = await asyncio.gather(*tasks, return_exceptions=True)

        papers: list[Paper] = []
        for result in results_nested:
            if isinstance(result, Exception) or isinstance(result, BaseException):
                _log.warning("discovery_source_error", error=str(result))
                continue
            if isinstance(result, list):
                papers.extend(result)

        return papers


# ---------------------------------------------------------------------------
# Citation-key helpers (also used by Librarian)
# ---------------------------------------------------------------------------


def _normalise_author(name: str) -> str:
    """Return lowercase alphanumeric last-name fragment from a full author name.

    Handles both 'Last, First' (BibTeX style) and 'First Last' formats.
    """
    name = name.strip()
    if "," in name:
        # 'Smith, Jane' or 'O\'Brien, Alice' — take the part before the comma.
        last = name.split(",")[0].strip()
    else:
        # 'Jane Smith' — take the last word.
        parts = name.split()
        last = parts[-1] if parts else "unknown"
    return re.sub(r"[^a-z0-9]", "", last.lower())


def generate_citation_keys(papers: list[Paper]) -> list[Paper]:
    """Assign unique BibTeX citation keys to a list of papers (in-place copy).

    Format: ``firstauthorlastnameYEAR`` with ``a``, ``b``, ... disambiguation.
    Returns new Paper objects (Pydantic models are immutable by default).
    """
    seen: dict[str, int] = {}
    updated: list[Paper] = []
    for paper in papers:
        author = paper.authors[0] if paper.authors else "unknown"
        year = str(paper.year) if paper.year else "nd"
        base_key = f"{_normalise_author(author)}{year}"

        count = seen.get(base_key, 0)
        seen[base_key] = count + 1
        if count == 0:
            suffix = ""
        elif count <= 26:
            suffix = chr(ord("a") + count - 1)
        else:
            suffix = f"-{count}"
        key = f"{base_key}{suffix}"

        updated.append(paper.model_copy(update={"citation_key": key}))

    return updated
