"""Manuscript export service — BRD FR-3.5 + §10 (AI-disclosure/audit appendix).

Builds student-submission-ready exports from the DB (manuscript artifact,
approved-pool papers, audit log) — decoupled from the LangGraph internals so it
can be unit-tested against a plain session. Four formats:

  - markdown : the assembled manuscript text.
  - bibtex   : a .bib of the approved pool ONLY (FR-2.4 citation invariant).
  - package  : a ZIP of separate files (manuscript / references / disclosure /
               audit appendix).
  - bundle   : the same content as one combined markdown file.

LaTeX is intentionally NOT a format here (v0.2). The route's allowed-format set
excludes it, so a `latex` request is an ordinary validation error.
"""

from __future__ import annotations

import io
import zipfile
from datetime import UTC
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.db import ArtifactRow, AuditLogRow, PaperRow

# The formats the export endpoint accepts. Single source of truth — the route
# validates against this, and the package/bundle builders use it.
EXPORT_FORMATS: tuple[str, ...] = ("markdown", "bibtex", "package", "bundle")


class ManuscriptNotReadyError(RuntimeError):
    """Raised when an export is requested before a manuscript artifact exists."""


async def _approved_papers(db: AsyncSession, project_id: UUID) -> list[PaperRow]:
    rows = (
        await db.execute(
            select(PaperRow)
            .where(PaperRow.project_id == project_id, PaperRow.approved.is_(True))
            .order_by(PaperRow.citation_key)
        )
    ).scalars()
    return list(rows)


async def _manuscript(db: AsyncSession, project_id: UUID) -> ArtifactRow:
    row = (
        (
            await db.execute(
                select(ArtifactRow)
                .where(ArtifactRow.project_id == project_id, ArtifactRow.kind == "manuscript")
                .order_by(ArtifactRow.created_at.desc())
                .limit(1)
            )
        )
        .scalars()
        .first()
    )
    if row is None:
        raise ManuscriptNotReadyError(
            "No manuscript artifact exists yet — finish Phase 4 (drafting) first."
        )
    return row


def _bibtex_entry(paper: PaperRow) -> str:
    """One @article entry from a PaperRow. Defensive on missing metadata."""
    authors = " and ".join(str(a) for a in (paper.authors or []) if str(a).strip())
    fields = [f"  title        = {{{paper.title or 'Untitled'}}}"]
    if authors:
        fields.append(f"  author       = {{{authors}}}")
    if paper.year:
        fields.append(f"  year         = {{{paper.year}}}")
    if paper.pdf_url:
        fields.append(f"  url          = {{{paper.pdf_url}}}")
    # external_id is a DOI for many sources — surface it as a note/doi field.
    if paper.external_id:
        fields.append(f"  note         = {{{paper.source}:{paper.external_id}}}")
    body = ",\n".join(fields)
    return f"@article{{{paper.citation_key},\n{body}\n}}"


async def build_bibtex(db: AsyncSession, project_id: UUID) -> str:
    """BibTeX of the approved pool only (FR-2.4 — cite only from the pool)."""
    papers = await _approved_papers(db, project_id)
    if not papers:
        return "% No approved papers in the pool.\n"
    header = "% References — ResearchFlow AI approved pool (cite-only-from-pool).\n\n"
    return header + "\n\n".join(_bibtex_entry(p) for p in papers) + "\n"


async def build_audit_appendix(db: AsyncSession, project_id: UUID) -> str:
    """Human-readable audit trail — the BRD §10 AI-disclosure/audit appendix.

    Lists every recorded action (agent invocations, approvals, rejections,
    overrides, citation corrections) with timestamp, actor, model, and
    token/cost where present. This is what a student attaches to a submission
    to disclose exactly what the AI did.
    """
    rows = (
        await db.execute(
            select(AuditLogRow)
            .where(AuditLogRow.project_id == project_id)
            .order_by(AuditLogRow.created_at)
        )
    ).scalars()
    lines = [
        "## AI-disclosure & audit appendix",
        "",
        "Every agent invocation and human decision recorded for this project, "
        "in order. Generated by ResearchFlow AI for academic-integrity "
        "disclosure (BRD §10).",
        "",
        "| When (UTC) | Actor | Action | Model | Tokens (in/out) | Cost USD |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        when = r.created_at.astimezone(UTC).strftime("%Y-%m-%d %H:%M:%S")
        tin = r.tokens_in if r.tokens_in is not None else ""
        tout = r.tokens_out if r.tokens_out is not None else ""
        toks = f"{tin}/{tout}" if (tin != "" or tout != "") else "—"
        cost = f"{r.cost_usd:.4f}" if r.cost_usd is not None else "—"
        model = r.model or "—"
        lines.append(f"| {when} | {r.actor} | {r.action} | {model} | {toks} | {cost} |")
    return "\n".join(lines) + "\n"


def _disclosure_note(approved_count: int) -> str:
    """Standalone disclosure note for the export (mirrors the in-manuscript one
    the assembler prepends; duplicated here so the export file is self-contained
    even if the manuscript markdown is edited later)."""
    s = "s" if approved_count != 1 else ""
    return (
        "## AI-generated review — disclosure\n\n"
        "> This manuscript was produced by an automated multi-agent pipeline "
        "(ResearchFlow AI) with a human in the loop at every phase boundary. "
        f"A human approved **{approved_count} paper{s}** as the working pool; "
        "an LLM drafted each section, gated by human approval. All claims should "
        "be read as observations within this AI-curated sample.\n"
    )


def _slug(title: str) -> str:
    keep = [c.lower() if c.isalnum() else "-" for c in (title or "manuscript")]
    out = "".join(keep).strip("-")
    while "--" in out:
        out = out.replace("--", "-")
    return out or "manuscript"


async def build_package_zip(db: AsyncSession, project_id: UUID, title: str) -> bytes:
    """ZIP of separate files: manuscript, references, disclosure, audit appendix.

    Deterministic file names under a `<slug>/` directory.
    """
    manuscript = await _manuscript(db, project_id)
    papers = await _approved_papers(db, project_id)
    bib = await build_bibtex(db, project_id)
    appendix = await build_audit_appendix(db, project_id)
    disclosure = _disclosure_note(len(papers))
    slug = _slug(title)

    buf = io.BytesIO()
    # Fixed timestamp + no compression metadata variance → deterministic bytes
    # for a given input (helps the "deterministic file naming" test).
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{slug}/manuscript.md", manuscript.content)
        zf.writestr(f"{slug}/references.bib", bib)
        zf.writestr(f"{slug}/ai-disclosure.md", disclosure)
        zf.writestr(f"{slug}/audit-appendix.md", appendix)
    return buf.getvalue()


async def build_bundle_markdown(db: AsyncSession, project_id: UUID) -> str:
    """Single combined markdown file: disclosure + manuscript + references +
    audit appendix, separated by horizontal rules. The non-ZIP option."""
    manuscript = await _manuscript(db, project_id)
    papers = await _approved_papers(db, project_id)
    bib = await build_bibtex(db, project_id)
    appendix = await build_audit_appendix(db, project_id)
    disclosure = _disclosure_note(len(papers))
    parts = [
        disclosure,
        "---",
        manuscript.content,
        "---",
        "## References (BibTeX)\n\n```bibtex\n" + bib + "```\n",
        "---",
        appendix,
    ]
    return "\n\n".join(parts)


async def build_manuscript_markdown(db: AsyncSession, project_id: UUID) -> str:
    """Just the assembled manuscript text."""
    return (await _manuscript(db, project_id)).content
